frontend/models/Product.php
<?php

namespace frontend\models;

use yii;
use common\models\User;

class Product extends \yii\db\ActiveRecord {

    public static function tableName() {
        return 'product';
    }

    public function rules() {
        return [

            [['name', 'category', 'specification'], 'required'],
            [['name'], 'string', 'max' => 30],
            [['model_no', 'image'], 'string'],
            [['company_id'], 'integer'],
        ];
    }

    public function attributeLabels() {
        return [
            'name' => 'Product Name',
            'category' => 'Category',
            'image' => 'Upload Product Image',
            'specification' => 'Specification',
            'model_no' => 'Model No.',
        ];
    }

    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'company_id']);
    }

}

frontend/controllers/ProductController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Address;
use frontend\models\Category;
use frontend\models\Contact_person;
use frontend\models\Product;
use yii\web\UploadedFile;

/**
 * Product controller
 */
class ProductController extends Controller {

    public function actionIndex() {

        $id = \Yii::$app->user->identity->id;
        $category = Category::find()->all();
        $model = new Product;
        $product = Product::find()->where(['company_id' => $id])->all(); // all() get error[call to a member function load() on array]
        // echo "<pre>";
        // var_dump($model);
        // echo "</pre>";
        //  exit();

        if ($model->load(\yii::$app->request->post()) && $model->validate()) {

            $image = UploadedFile::getInstance($model, 'image');

            $image->saveAs('uploads/product/' . $image->baseName . '.' . $image->extension);
            $model->image = $image->baseName . '.' . $image->extension;
            $model->save();
            if ($model->save()) {
                return $this->redirect(['product/index']);
            }
        }
        return $this->render('product', ['model' => $model, 'category' => $category, 'product' => $product]);
    }

    public function actionDetails($id) {
        $category = Category::find()->all();
        $model = Product::find()->where(['id' => $id])->one();

        if ($model->load(\yii::$app->request->post()) && $model->validate()) {
            $image = UploadedFile::getInstance($model, 'image');

            $image->saveAs('uploads/product/' . $image->baseName . '.' . $image->extension);
            $model->image = $image->baseName . '.' . $image->extension;
            $model->save();
        }

        return $this->render('product_details', ['model' => $model, 'category' => $category]);
    }

}

frontend/views/product/product.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use frontend\models\Address;
use yii\helpers\Url;



$this->title= 'Product List';
// $profile = $model->profile;
//  echo "ok";
//  echo "<pre>";
// 	   	var_dump($model);
//  	   	echo "</pre>";
// 	  	exit();
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="container">
    	<div class="row">
    		<div class="col-md-8">
    			<table class="table">
    				<tr>
    				<td>Sl.</td>
    				<td>Name</td>
    				<td>Specification</td>
    				<td>Model No.</td>
                    <td>Action</td>
    				</tr>
                    <?php 
                        if(!empty($product)){
                            $i=1;
                            foreach ($product as $value) {
                    ?>
                    <tr>
                    <td><?= $i;?></td>
                    <td><?= $value->name;?></td>
                    <td><?= $value->specification;?></td>
                    <td><?= $value->model_no;?></td>
                    <td><a class="btn btn-sm btn-primary" href="<?= Url::toRoute(['product/details','id'=>$value->id]);?>">Deails</a></td>
                    </tr>
                   <?php       $i++;  }
                        }
                    ?>
    				
    			</table>
    		</div>
            <?php
            $cat_option=[];
                if(!empty($category)){
                    foreach ($category as $value) {
                        $cat_option[$value->id] = $value->name;
                    }
                }
            ?>
    		<div class="col-md-4">
    			<h3>Add New Product</h3>
					<?php $form= ActiveForm::begin(['id'=>'product-form']); ?>
					<?= $form->field($model,'name')->textInput(); ?>
					<?= $form->field($model,'category')->dropDownList($cat_option,['prompt'=>'Select Option']); ?>
					<?= $form->field($model, 'image')->fileInput() ?>
					<?= $form->field($model,'model_no')->textInput(); ?>
                    <?= $form->field($model, 'specification')->textarea(['row' => 5]) ;?>
		        	<?= $form->field($model, 'company_id')->hiddenInput(['value'=>\Yii::$app->user->identity->id])->label(false);?>

		        	<div class="form-group">
		                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
		            </div>

		            <?php ActiveForm::end(); ?>
			</div>
    		</div>
    	</div>
    </div>
</div>

frontend/views/product/product_details.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use frontend\models\Address;
use yii\helpers\Url;



$this->title= 'Product View';
// $profile = $model->profile;
//  echo "ok";
//  echo "<pre>";
// 	   	var_dump($model);
//  	   	echo "</pre>";
// 	  	exit();
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="container">
    	<div class="row">
    		<div class="col-md-8">
    			<table class="table">
    				<tr><td><img width="200px" src="<?= Yii::$app->request->baseUrl.'/uploads/product/'.$model->image;?>"></td><td></td></tr>
                    <tr><td>Name:</td><td><?=$model->name;?></td></tr>
                    <tr><td>Category:</td><td></td></tr>
                    <tr><td>Model No.</td><td><?=$model->model_no;?></td></tr>
                    <tr><td>Specification:</td><td><?=$model->specification;?></td></tr>
    			</table>
    		</div>
            <?php
            $cat_option=[];
                if(!empty($category)){
                    foreach ($category as $value) {
                        $cat_option[$value->id] = $value->name;
                    }
                }
            ?>
    		<div class="col-md-4">
    			<h3>Edit Product</h3>
					<?php $form= ActiveForm::begin(['id'=>'product-form']); ?>
					<?= $form->field($model,'name')->textInput(); ?>
					<?= $form->field($model,'category')->dropDownList($cat_option,['prompt'=>'Select Option']); ?>
					<?= $form->field($model, 'image')->fileInput() ?>
					<?= $form->field($model,'model_no')->textInput(); ?>
                    <?= $form->field($model, 'specification')->textarea(['row' => 5]) ;?>
		        	<?= $form->field($model, 'company_id')->hiddenInput(['value'=>\Yii::$app->user->identity->id])->label(false);?>

		        	<div class="form-group">
		                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
		            </div>

		            <?php ActiveForm::end(); ?>
			</div>
    	</div>
    </div>
</div>